### ISSUE TITLE
Error installing Django 1.8

### ISSUE THREAD

**Issue by mykljohn** [funkybob/django-grappelli-template-editor#9]
I'm trying to install this, I did the pip install no problem, but in in your installation instructions, you say to:

Add to INSTALLED_APPS

which I did and got the following error "ImportError: No module named django-grappelli-template-editor". I've obviously made an error :( Any help would be great.

**Comment by funkybob** [comment]
I've clarified the README

**Comment by mykljohn** [comment]
thx.  That helped :)  question now...I don't have any templates.  To edit the admin templates, should I copy them to my templates dir? Because I copied them to the /templates/admin and still can't see them.

**Comment by funkybob** [comment]
Did you add that templates dir to the TEMPLATE_DIRS list in settings?

**Comment by mykljohn** [comment]
Hi, I have   'DIRS': [os.path.join(BASE_DIR, 'templates'),'/home/mykl/mysite/myapp/templates'],

**Comment by funkybob** [comment]
Ah, of course... 1.8...

I suppose I should add an explicit setting for this instead of piggy-backing.

this project was never meant to be taken that seriously anyway :)

**Comment by mykljohn** [comment]
Sorry, I'm having issues with the look of Grappelli, so I thought I'd look at this and see if  I could improve the layout.  Question you may know, the css for Grappelli is all one line...is ther a utility I can use to edit it. (scrolling the whole line to replace values is a pain in the ass. :)

**Comment by funkybob** [comment]
Ah... perhaps the name is misleading?  This is a template editor that depends on Grapelli... not an editor of Grapelli templates.

As for the CSS, it's most likely minified... so check the source package for the original files, as well as details of how it's minified.

**Comment by mykljohn** [comment]
darn, wishful thinking :)  I'll still take a look.  It may prove useful.  cheers
